"""add assessment_details to matchresult

Revision ID: ce93b95a47d2
Revises: 1a1759727c60
Create Date: 2026-08-28 23:28:54.711903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ce93b95a47d2'
down_revision: Union[str, Sequence[str], None] = '1a1759727c60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matchresult', sa.Column('assessment_details', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('matchresult', 'assessment_details')
    # ### end Alembic commands ###
